In [1]:
import numpy
import numpy as np

# 1. Create a 1D array of numbers from 0 to 9

In [3]:
arr = numpy.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


# 2. Calculate sum of the array

In [4]:
print(arr.sum())

45


In [5]:
print(numpy.sum(arr))

45


In [6]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())


9
0
4.5
2.8722813232690143


# 3. Create a different array with random 10 numbers

In [8]:
arr2 = numpy.random.rand(10)
print(arr2)

[0.31693846 0.94522254 0.7670123  0.6227892  0.22252546 0.76788293
 0.64312308 0.96165891 0.02387909 0.51081106]


# 4. Add arr and arr2

In [9]:
print(arr + arr2)

[0.31693846 1.94522254 2.7670123  3.6227892  4.22252546 5.76788293
 6.64312308 7.96165891 8.02387909 9.51081106]


# 5. Scalar Product of arr and arr2

In [11]:
print(numpy.dot(arr, arr2))

24.455814327491346


In [12]:
print(arr @ arr2)

24.455814327491346


# dot = a1*b1 + a2*b2 + a3*b3 + a4*b4 + a5*b5 + a6*b6 + a7*b7 + a8*b8 + a9*b9 + a10*b10

# 6. Generate array with zeros

In [13]:
arr3 = numpy.zeros(10)
print(arr3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
arr4 = numpy.zeros((3, 3))
print(arr4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 7. Generate matrix

In [19]:
matrix1 = numpy.random.rand(3, 3)
print(matrix1)

[[0.18027331 0.36246097 0.98646054]
 [0.77836924 0.26897515 0.54933282]
 [0.13804065 0.22421617 0.39191315]]


# 8. Generate matrix with ones on the diagonal

In [17]:
matrix2 = numpy.eye(3)
print(matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 9. Transpose matrix

In [20]:
print(matrix1.T)

[[0.18027331 0.77836924 0.13804065]
 [0.36246097 0.26897515 0.22421617]
 [0.98646054 0.54933282 0.39191315]]


# 10. Add matrixes

In [21]:
print(matrix1 + matrix2)

[[1.18027331 0.36246097 0.98646054]
 [0.77836924 1.26897515 0.54933282]
 [0.13804065 0.22421617 1.39191315]]


# 11. Multiply matrixes

In [22]:
print(matrix1 @ matrix2)

[[0.18027331 0.36246097 0.98646054]
 [0.77836924 0.26897515 0.54933282]
 [0.13804065 0.22421617 0.39191315]]


# 12. Find matrix determinant

In [23]:
print(numpy.linalg.det(matrix1))

0.049248242105876236


In [24]:
print(numpy.linalg.det(matrix2))

1.0


In [ ]:
# 13. Find matrix inverse

In [25]:
inversed = numpy.linalg.inv(matrix1)

In [26]:
print(inversed)

[[-0.36050842  1.60670077 -1.34465031]
 [-4.65443775 -1.33040635 13.5801901 ]
 [ 2.78981466  0.19521826 -4.74411712]]


In [27]:
print(matrix1 @ inversed)

[[ 1.00000000e+00 -4.35242927e-18 -5.63464834e-16]
 [-1.59930441e-18  1.00000000e+00  2.01757727e-16]
 [-1.13288436e-16 -1.59478244e-17  1.00000000e+00]]


# 14. Solve linear system

# 3x + 2y = 1
# 4x + 5y = 2

In [28]:
A = numpy.array([[3, 2], [4, 5]])
B = numpy.array([1, 2])

In [29]:
print(numpy.linalg.solve(A, B))

[0.14285714 0.28571429]


# 15. Solve quadratic equation

# x^2 - 4x + 3 = 0

In [30]:
print(numpy.roots([1, -4, 3]))

[3. 1.]


In [31]:
print(numpy.roots([1, 1, -4, 3]))

[-2.80630072+0.j          0.90315036+0.50333133j  0.90315036-0.50333133j]


# 16. Find eigenvalues and eigenvectors

In [32]:
eigenvalues, eigenvectors = numpy.linalg.eig(matrix1)

In [33]:
print(eigenvalues)

[ 1.15305158+0.j         -0.15594499+0.13561852j -0.15594499-0.13561852j]


# Власні числа (Eigenvalues)
Власне число матриці 
�
A - це скаляр 
�
λ, який задовольняє рівняння 
�
�
=
�
�
Av=λv, де 
�
v - це ненульовий вектор. Іншими словами, коли матриця 
�
A діє на вектор 
�
v, результатом є масштабований вектор, який є паралельним до 
�
v, і 
�
λ є масштабувальним фактором.

Власні вектори (Eigenvectors)
Власний вектор 
�
v матриці 
�
A - це ненульовий вектор, який, коли множиться на матрицю 
�
A, просто масштабується на власне число 
�
λ, тобто 
�
�
=
�
�
Av=λv. Власні вектори вказують напрямки, в яких застосування матриці 
�
A просто "витягує" або "стискає" вектор, замість того, щоб змінити його напрямок.

In [35]:
array = numpy.array([[1, 2, 3, 4]])

# 17. Filter values which is more that 2

In [36]:
print(array[array > 2])

[3 4]


In [37]:
# 18. Find index of max value

In [38]:
print(numpy.argmax(array))

3
